### PR TITLE
Organize tests and test custom css js dirs

### PR DESCRIPTION
**Pull request by lgp171188**
This pull request organizes the tests into a separate ``tests`` module and integrates the them with ``setup.py`` so that the tests can be run using ``python setup.py test``.

The packages required for running the tests are listed in ``test_requirements.txt`` and included in the ``tests_require`` option of ``setup.py``

### CODE REVIEW

**Comment by areski** [comment]
Best contribution I saw to the project in a very long time, thanks for that!

**Comment by areski** [comment]
Hi @lgp171188 
The tests are failing at https://github.com/areski/django-nvd3/blob/develop/tests/test_template_tags.py#L50 with Django 1.9, any idea how to solve this?

**Comment by lgp171188** [comment]
Looks like some issue with the getting Django ready before running that code. Will check and get back with a fix.

**Comment by lgp171188** [comment]
@areski Please review the fix and merge it if it is okay - https://github.com/areski/django-nvd3/pull/71

**Comment by areski** [comment]
Thanks I merged #71 but it doesnt seems to fix the initial problem

**Comment by lgp171188** [comment]
@areski I see that the Python 3.3 build fails (https://travis-ci.org/areski/django-nvd3/jobs/96027438) when trying to load the tests. Will try to debug what the issue is. But Django 1.9 doesn't support Python 3.3. So I'm not sure if it can be fixed.

**Comment by areski** [comment]
ok great, I should have checked the details! Thanks a lot for your fix!

On Thu, Dec 10, 2015 at 2:27 PM, Guruprasad <notifications@github.com>
wrote:

> @areski <https://github.com/areski> I see that the Python 3.3 build fails
> (https://travis-ci.org/areski/django-nvd3/jobs/96027438) when trying to
> load the tests. Will try to debug what the issue is. But Django 1.9 doesn't
> support Python 3.3. So I'm not sure if it can be fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/areski/django-nvd3/pull/65#issuecomment-163614094>.
>



-- 
Kind regards,
/Areski

----
Arezqui Belaid, <areski@gmail.com>
Founder at Star2Billing (www.star2billing.com)

Tel: +34650784355
Twitter: http://twitter.com/areskib
LinkedIn: http://www.linkedin.com/in/areski

**Comment by lgp171188** [comment]
@areski I debugged the issue and found that Django 1.9 uses some new features added in Python 3.4 (since 3.3 is no longer supported) which breaks the way tests are imported. I can confirm that the tests on Python 3.3 with Django 1.8.7 pass.

**Comment by areski** [comment]
Thanks I just remove py3.3 support in travis!
:+1:

**Comment by lgp171188** [comment]
@areski In case you want to keep Python 3.3 for testing Django 1.8.x which is the LTS release and is supported for a long time, pull request https://github.com/areski/django-nvd3/pull/72. If you don't want to ensure that django-nvd3 works on Django 1.8.x, then it is fine :)

**Comment by areski** [comment]
you convinced me with the LTS ;)

**Pull request merged**
